HowToTrainYourDragon.MVC/Controllers/DragonController.cs
using HowToTrainYourDragon.Data;
using HowToTrainYourDragon.Model.DragonModel;
using HowToTrainYourDragon.Service;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HowToTrainYourDragon.MVC.Controllers
{
    public class DragonController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        // GET: Dragon
        public ActionResult Index()
        {
            //var userId = Guid.Parse(User.Identity.GetUserId());
            //var service = new DragonService(userId);
            //var model = service.GetDragons();

            var service = new DragonService();
            var model = service.GetDragons();
            return View(model);
        }

        public ActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(DragonCreate dragon)
        {
            if (!ModelState.IsValid)
            {
                return View(dragon);
            }

            HttpPostedFileBase file = Request.Files["ImageData"];
            
            var service = CreateDragonService();
          
            if (service.CreateDragon(file, dragon))
            {
                TempData["SaveREsult"] = "Your dragon was created";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Dragon could not be created");

           return View(dragon);

        }

        public ActionResult Details(int id)
        {
            var service = new DragonService();
            var model = service.GetDragonById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateDragonService();
            var detail = service.GetDragonById(id);
            var model = new DragonEdit
            {
                DragonId = detail.DragonId,
                DragonType = detail.DragonType,
                Color = detail.Color,
                Image = detail.Image,
               
                CurrentLocatonId = detail.CurrentLocationId
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(int id, DragonEdit dragon)
        {
            if (!ModelState.IsValid)
            {
                return View(dragon);
            }
            if(dragon.DragonId != id)
            {
                ModelState.AddModelError("", " Id Mismatch");
                return View(dragon);
            }


            HttpPostedFileBase file = Request.Files["ImageData"];
            var service = CreateDragonService();
            if (service.UpdateDragon(file, dragon))
            {
                TempData["SaveResult"] = "Your Dragon was updated";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your dragon could not be updated");
            return View(dragon);
        }

        [ActionName("Delete")]

        public ActionResult Delete(int id)
        {
            var service = CreateDragonService();
            var model = service.GetDragonById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public ActionResult DeleteDragon(int id)
        {
            var service = CreateDragonService();

            service.DeleteDragon(id);

            TempData["SaveResult"] = "Your dragon was delete";
            return RedirectToAction("Index");
        }

        public ActionResult RetrieveImage(int id)
        {
            var service = CreateDragonService();


            byte[] cover = service.GetImageFromDatabase(id);
            if(cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        private DragonService CreateDragonService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new DragonService(userId);
            return service;
        }
    }
}

HowToTrainYourDragon.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HowToTrainYourDragon.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HowToTrainYourDragon.MVC/Controllers/HumanController.cs
using HowToTrainYourDragon.Model.HumanModel;
using HowToTrainYourDragon.Service;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HowToTrainYourDragon.MVC.Controllers
{
    public class HumanController : Controller
    {
        // GET: Human
        public ActionResult Index()
        {
            //var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new HumanService();
            var model = service.GetHumans();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(HumanCreate model)
        {
            if (!ModelState.IsValid)
                return View(model);

            HttpPostedFileBase file = Request.Files["ImageData"];
            var service = CreateHumanService();

            if (service.CreateHuman(file, model))
            {
                TempData["SaveReslt"] = "You have posted character";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Human could not be created");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = new HumanService();
            var model = service.GetHumanById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateHumanService();
            var detail = service.GetHumanById(id);
            var model = new HumanEdit
            {
                HumanId = detail.HumanId,
                Name = detail.Name,
                Occupation = detail.Occupation,
                CurrentLocationId = detail.CurrentLocationId,
                DragonCompanionId = detail.DragonCompanionId,
                IsEvil = detail.IsEvil,
                Image = detail.Image,
                Gender = detail.Gender,
                HairColor = detail.HairColor,
                EyeColor = detail.EyeColor,
                HasDragon = detail.HasDragon
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, HumanEdit model)
        {
            if (!ModelState.IsValid)
                return View(model);
            if (model.HumanId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            HttpPostedFileBase file = Request.Files["ImageData"];
            var service = CreateHumanService();
            if (service.UpdateHuman(file, model))
            {
                TempData["SaveResult"] = "Your note was updated";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Your note could be updated");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateHumanService();
            var model = svc.GetHumanById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteHuman(int id)
        {
            var service = CreateHumanService();

            service.DeleteHuman(id);

            TempData["SaveResult"] = "Your note was deleted";
            return RedirectToAction("Index");
        }

        public ActionResult RetrieveImage(int id)
        {
            var service = CreateHumanService();


            byte[] cover = service.GetImageFromDatabase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        private HumanService CreateHumanService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new HumanService(userId);
            return service;
        }
    }

    
}

HowToTrainYourDragon.MVC/Controllers/LocationController.cs
using HowToTrainYourDragon.Data;
using HowToTrainYourDragon.Model.LocationModel;
using HowToTrainYourDragon.Service;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HowToTrainYourDragon.MVC.Controllers
{
    public class LocationController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        // GET: Location
        public ActionResult Index()
        {
            //var userId = Guid.Parse(User.Identity.GetUserId());
            //var service = new LocationService(userId);
            // var model = service.GetLocations();
            var service = new LocationService();
            var model = service.GetLocations();
            return View(model);
        }

        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(LocationCreate location)
        {
            if (!ModelState.IsValid)
            {
                return View(location);
            }

            var service = CreateLocationService();
            if (service.CreateLocation(location))
            {
                TempData["SaveResult"] = "Your Location was created";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Location could not be created");

            return View(location);
        }

        public ActionResult Details(int id)
        {
            var service = new LocationService();
            var model = service.GetLocationById(id);

            

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateLocationService();
            var detail = service.GetLocationById(id);
            var model = new LocationEdit
            {
                LocationId = detail.LocationId,
                LocationName = detail.LocationName,
                AlternateName = detail.AlternateName

            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(int id, LocationEdit location)
        {
            if (!ModelState.IsValid)
                return View(location);
            if(location.LocationId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(location);
            }
            var service = CreateLocationService();
            if (service.UpdateLocation(location))
            {
                TempData["SaveResult"] = "Your location was updated";
                return RedirectToAction("Index");

            }
            ModelState.AddModelError("", "YOur could not be updated");
            return View(location);

        }

        [ActionName("Delete")]

        public ActionResult Delete(int id)
        {
            var svc = CreateLocationService();
            var model = svc.GetLocationById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public ActionResult DeleteLocatoin(int id)
        {
            var service = CreateLocationService();

            service.DeleteLocation(id);

            TempData["SaveResult"] = "Your location was deleted";
            return RedirectToAction("Index"); 
        }

       private LocationService CreateLocationService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LocationService(userId);
            return service;
        }
    }
}

HowToTrainYourDragon.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<body style="background-image: url('../../Images/background7.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; background-color: black; color: white; font-family: Papyrus, fantasy;">

    <h2>About This Database</h2>


    <p> Do you love the "How To Train Your Dragon" franchise? You want to learn more about it? Or did you stumble upon this site and thought it interesting? Well welcome to my "How To Train Your Dragon" Database! Where you will learn more about the world that makes the franchise so iconic and beloved by many.</p>
    <p> I am a newish coder in the world of programming. This database is in face my final project. I wanted to do a project about something I cared about. I thought long and hard, and I landed on doing a How To Train Your Dragon Database. This has been a heck of a 3 weeks it took me to make it. My blood, sweat, and tears, but mostly tears have made this site the way it is. There are four categories: Locations, Humans, Dragons, and Partnerships. </p>
    <p> Locations will display all the locations, and within each location you can see lists of the dragons and humans that currently live there, based on the franchise. There may be a lot, there may a none at all. But you can help fill it out or edit it! </p>
    <p> Dragons will display all the dragons. It has the species, classes, and their stats that the vikings have giving them. You can help fill this out as well!</p>
    <p> Humans will be all the human characters. This where you'll see if they have a dragon or if they are evil. Some people flip back and forth between evil and not so bad, so editing can be a pain.</p>
    <p> Partnerships will just be one list of all the human and dragons duos! That table relies on human and dragons to be completed!</p>
    <p> This franchise has been a big part of my life ever since I was younger. As I grown, the movies and shows have done the same. It has been a heck of ride and I want to share with you guys</p>
</body>

HowToTrainYourDragon.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<body style="background-image: url('../../Images/background7.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; background-color: black; color: white; font-family: Papyrus, fantasy;">

    <h2>Contact Me.</h2>




    <address ">
        <strong>Email:</strong>   <a style="color:white;"href="smreilly22@gmail.com">smreilly22@gmail.com</a><br />
    </address>
</body>

HowToTrainYourDragon.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<body style="background-image: url('../../Images/BERK2.jpeg'); background-repeat: no-repeat; background-attachment:fixed; background-size: cover;">
    

    <div class="jumbotron" style="font-family: Papyrus, fantasy; border: solid; border-color: white; background-color: black; color: white;">
        <h1>How To Train Your Dragon</h1>
        <p class="lead">This is a How To Train Your Dragon Database where see all the characters, dragons, and locations from the franchise.</p>
        @Html.ActionLink("Learn More", "About")
    </div>

    <div class="row" style="color:white;">
        <div class="col-md-4" style="border: solid; border-color:white; background-color: deepskyblue; margin: 3em; font-family: Papyrus, fantasy;">
            <h2>Locations</h2>
            <p>
                Dive into the Locations that make the franchise so beautiful to look at.
            </p>
            @Html.ActionLink("Locations", "Index", "Location", null, new { @class = "btn btn-primary btn-small" })
        </div>
        <div class="col-md-4" style="border: solid; border-color: white; background-color: crimson; margin: 3em; font-family: Papyrus, fantasy;">
            <h2>Characters</h2>
            <p>See the Human Charaacters that you fell in love with(or you learn to hate).</p>
            @Html.ActionLink("Chracters", "Index", "Human", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-4" style="border: solid; border-color: white; background-color: darkcyan; margin: 3em; font-family: Papyrus, fantasy;">
            <h2>Dragons</h2>
            <p>See The AWESOME Dragons that made the franchise so iconic.</p>
            @Html.ActionLink("Dragons", "Index", "Dragon", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-4" style="border: solid; border-color: white; background-color: darksalmon; margin: 3em; font-family: Papyrus, fantasy;">
            <h2>Partnerships</h2>
            <p>See a List of Human Riders and Dragon Companion Duos.</p>
            @Html.ActionLink("Partnerships", "Index", "Partnerships", null, new { @class = "btn btn-primary btn-large" })
        </div>
    </div>
</body>